In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Model
from keras import models

In [8]:
input_img = keras.Input(shape=(28, 28, 1))
input_enc = keras.Input(shape=(4, 4, 8))

x = layers.Conv2D(16, (3, 3), activation='relu', padding='same')(input_img)
x = layers.MaxPooling2D((2, 2), padding='same')(x)
x = layers.Conv2D(8, (3, 3), activation='relu', padding='same')(x)
x = layers.MaxPooling2D((2, 2), padding='same')(x)
x = layers.Conv2D(8, (3, 3), activation='relu', padding='same')(x)
encoded = layers.MaxPooling2D((2, 2), padding='same')(x)

encoder = keras.Model(input_img, encoded)
# at this point the representation is (4, 4, 8) i.e. 128-dimensional

x = layers.Conv2D(8, (3, 3), activation='relu', padding='same')(input_enc)
x = layers.UpSampling2D((2, 2))(x)
x = layers.Conv2D(8, (3, 3), activation='relu', padding='same')(x)
x = layers.UpSampling2D((2, 2))(x)
x = layers.Conv2D(16, (3, 3), activation='relu')(x)
x = layers.UpSampling2D((2, 2))(x)
decoded = layers.Conv2D(1, (3, 3), activation='sigmoid', padding='same')(x)
decoder = keras.Model(input_enc, decoded)

enc = encoder(input_img)
dec = decoder(enc)


autoencoder = keras.Model(input_img, dec)
autoencoder.compile(optimizer='adam', loss='binary_crossentropy')

In [9]:
autoencoder.summary()

Model: "model_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         [(None, 28, 28, 1)]       0         
_________________________________________________________________
model_10 (Functional)        (None, 4, 4, 8)           1904      
_________________________________________________________________
model_11 (Functional)        (None, 28, 28, 1)         2481      
Total params: 4,385
Trainable params: 4,385
Non-trainable params: 0
_________________________________________________________________


In [10]:
from keras.datasets import mnist
import numpy as np

(x_train, _), (x_test, _) = mnist.load_data()

x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.
x_train = np.reshape(x_train, (len(x_train), 28, 28, 1))
x_test = np.reshape(x_test, (len(x_test), 28, 28, 1))


In [11]:
print(x_train.shape)

(60000, 28, 28, 1)


In [12]:


autoencoder.fit(x_train, x_train,
                epochs=1,
                batch_size=128,
                shuffle=True,
                validation_data=(x_test, x_test))


469/469 [==============================] - 43s 91ms/step - loss: 0.2243 - val_loss: 0.1425


In [16]:
a=encoder.predict(x_train[0:1,:])

In [21]:
print(a.shape)

(1, 4, 4, 8)


In [22]:
a1=np.reshape(a,(1,128))
a2=np.reshape(a1,(1,4,4,8))

In [23]:
print(decoder.predict(a2))

[[[[4.95143437e-09]
   [1.68733614e-12]
   [3.29945619e-12]
   [1.40865089e-11]
   [2.33135351e-11]
   [3.53794528e-11]
   [3.37124668e-11]
   [3.18843042e-11]
   [3.31199894e-11]
   [5.46103163e-11]
   [8.38395742e-11]
   [1.24366670e-10]
   [1.74173662e-10]
   [2.86480561e-10]
   [4.27211488e-10]
   [9.36026701e-10]
   [3.48376239e-09]
   [1.36805038e-08]
   [4.88638214e-08]
   [1.12094945e-07]
   [2.19398416e-07]
   [4.27178747e-07]
   [7.24225174e-07]
   [1.61846867e-06]
   [4.75227353e-06]
   [2.77945742e-06]
   [2.24965652e-06]
   [1.50819242e-05]]

  [[2.05722678e-12]
   [1.62056542e-18]
   [7.05430793e-18]
   [7.14517488e-17]
   [3.13538854e-16]
   [8.85856226e-16]
   [9.09357949e-16]
   [1.16617421e-15]
   [1.75024747e-15]
   [4.06115071e-15]
   [1.23206905e-14]
   [2.23675364e-14]
   [4.86691782e-14]
   [8.65398993e-14]
   [2.01415206e-13]
   [7.69741855e-13]
   [7.65766443e-12]
   [6.96198169e-11]
   [6.18020080e-10]
   [1.77732717e-09]
   [3.59847840e-09]
   [9.94111993e-09

In [17]:
b=decoder.predict(a)

In [18]:
print(b)

[[[[4.95143437e-09]
   [1.68733614e-12]
   [3.29945619e-12]
   [1.40865089e-11]
   [2.33135351e-11]
   [3.53794528e-11]
   [3.37124668e-11]
   [3.18843042e-11]
   [3.31199894e-11]
   [5.46103163e-11]
   [8.38395742e-11]
   [1.24366670e-10]
   [1.74173662e-10]
   [2.86480561e-10]
   [4.27211488e-10]
   [9.36026701e-10]
   [3.48376239e-09]
   [1.36805038e-08]
   [4.88638214e-08]
   [1.12094945e-07]
   [2.19398416e-07]
   [4.27178747e-07]
   [7.24225174e-07]
   [1.61846867e-06]
   [4.75227353e-06]
   [2.77945742e-06]
   [2.24965652e-06]
   [1.50819242e-05]]

  [[2.05722678e-12]
   [1.62056542e-18]
   [7.05430793e-18]
   [7.14517488e-17]
   [3.13538854e-16]
   [8.85856226e-16]
   [9.09357949e-16]
   [1.16617421e-15]
   [1.75024747e-15]
   [4.06115071e-15]
   [1.23206905e-14]
   [2.23675364e-14]
   [4.86691782e-14]
   [8.65398993e-14]
   [2.01415206e-13]
   [7.69741855e-13]
   [7.65766443e-12]
   [6.96198169e-11]
   [6.18020080e-10]
   [1.77732717e-09]
   [3.59847840e-09]
   [9.94111993e-09

In [20]:
print(autoencoder.predict(x_train[0:1,:]))

[[[[4.95143437e-09]
   [1.68733614e-12]
   [3.29945619e-12]
   [1.40865089e-11]
   [2.33135351e-11]
   [3.53794528e-11]
   [3.37124668e-11]
   [3.18843042e-11]
   [3.31199894e-11]
   [5.46103163e-11]
   [8.38395742e-11]
   [1.24366670e-10]
   [1.74173662e-10]
   [2.86480561e-10]
   [4.27211488e-10]
   [9.36026701e-10]
   [3.48376239e-09]
   [1.36805038e-08]
   [4.88638214e-08]
   [1.12094945e-07]
   [2.19398416e-07]
   [4.27178747e-07]
   [7.24225174e-07]
   [1.61846867e-06]
   [4.75227353e-06]
   [2.77945742e-06]
   [2.24965652e-06]
   [1.50819242e-05]]

  [[2.05722678e-12]
   [1.62056542e-18]
   [7.05430793e-18]
   [7.14517488e-17]
   [3.13538854e-16]
   [8.85856226e-16]
   [9.09357949e-16]
   [1.16617421e-15]
   [1.75024747e-15]
   [4.06115071e-15]
   [1.23206905e-14]
   [2.23675364e-14]
   [4.86691782e-14]
   [8.65398993e-14]
   [2.01415206e-13]
   [7.69741855e-13]
   [7.65766443e-12]
   [6.96198169e-11]
   [6.18020080e-10]
   [1.77732717e-09]
   [3.59847840e-09]
   [9.94111993e-09